### ISSUE TITLE
vagrant-vmware_desktop build is missing gawk

### ISSUE THREAD

**Issue by yfauser** [vmware/photon-packer-templates#1]
When running Vagrant up with the vmware desktop provider (fusion), the network configuration of Photon OS fails with:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv /tmp/bash: line 2: awk: command not found /etc/systemd/network/
```

This can be solved by installing gawk also for the vagrant-vmware_desktop image.

The vmware/photon box on atlas also is missing awk.

**Comment by frapposelli** [comment]
I'll take a look at it, thanks for reporting!

**Comment by frapposelli** [comment]
Can't reproduce with latest bits, please let me know if this is still a problem in your environment when using the latest version.
