### ISSUE TITLE
Version 2.0 GA fails to build for both VMware and Virtualbox after update

### ISSUE THREAD

**Issue by timothybrush** [vmware/photon-packer-templates#12]
Using `vars/iso-2.0GA.json` fails to build with either VMware or Virtualbox using the new Packer file. 

Suggest removing `vars/iso-2.0GA.json` or fixing to allow the older build to complete.

**Comment by tenthirtyam** [comment]
I experienced similar issues with VMware Photon OS 2.0 during the refactoring. After the refactor only 3.0+ and 4.0+ are included.

Ryan
