### ISSUE TITLE
Update repository to match 3.0 documentation.

### ISSUE THREAD

**Issue by jakemalley** [vmware/photon-packer-templates#5]
It would be good if you could update this repository with the files you list here: https://vmware.github.io/photon/assets/files/html/3.0/photon_user/packer-template.html

It's more than confusing that the above page links to this repo and the files just don't exist.

**Comment by kclinden** [comment]
agree

**Comment by mikeroySoft** [comment]
+1 on this... we're at 4.0 now and we still don't have a 3.0 for `iso-X.0GA.json`
Unless there's a new process now?

@ssahani @sharathjg @suezzelur

**Comment by suezzelur** [comment]
@gpiyush-dev can you take this up?

**Comment by gpiyush-dev** [comment]
Yes, I will take it up.

**Comment by gpiyush-dev** [comment]
Sorry for the late reply. Was caught up in between things. While working on the changes had a question - Are we using this project especially for vagrant or packer templates for photon in general?

**Comment by tenthirtyam** [comment]
This repository has been updated to work with newer releases of all components and refactored to HCL2. I'll work with @mikeroySoft to update the Photon OS 3.0 and 4.0 documentation to match the concepts now seen here in the project update.

Ryan

**Comment by tenthirtyam** [comment]
Deferring to https://github.com/vmware/photon/issues/1259.

Ryan

**Comment by tenthirtyam** [comment]
Closing as `status/will-not-fix` for this project as deferred to `vmware/photon`.

Ryan

**Comment by tenthirtyam** [comment]
Addressed in https://github.com/vmware/photon/issues/1259.

- 4.0: https://vmware.github.io/photon/docs/user-guide/packer-examples/
- 3.0: https://vmware.github.io/photon/docs-v3/user-guide/packer-examples/

Ryan
