### ISSUE TITLE
Update template with Hyper-V builder

### ISSUE THREAD

**Issue by cocowalla** [vmware/photon-packer-templates#7]
It's nice to have the VirtualBox builder in the template, rather than just including VMware support - it would be great to also include a builder for Hyper-V.

**Comment by tenthirtyam** [comment]
Hi @cocowalla,

Thanks for the enhancement suggestion - we can review the requirement to include this option. In the meantime, if you are in inclined, we are open to reviewing a pull request to add Hyper-V. 

Ryan
