### ISSUE TITLE
Support for Photon OS 4.0 GA

### ISSUE THREAD

**Issue by timothybrush** [vmware/photon-packer-templates#9]
The current repository doesn't appear to support Photon OS 4.0.

You might be able to leverage my new Packer template (https://github.com/timothybrush/packer-templates) under photon4 that uses Photon OS 4.0 GA to build out Vagrant boxes for each of the 4 different installation types (developer, minimal, ostree host, real time).  However, it currently only supports the vmware_desktop provider since I don't use or have Virtualbox installed.  

You might also find my [Vagrant Boxes](https://app.vagrantup.com/boxes/search?sort=updated&provider=vmware&q=timothybrush%2Fphoton) useful.

Notes: 
* Photon OS packages ~and OSTree~ show errors when upgrading to the latest versions. 
* ~OSTree Host installs but don't run `rpm-ostree update` to upgrade it.  The system will fail to restart.  This is an issue that the Photon OS team should investigate.~

**Comment by jaankit** [comment]
Hi @timothybrush,

i tried on `rpm-ostree update` command on 4.0 Ostree Host VM. It works without any issue.  Tried with [4.0 GA ISO](https://packages.vmware.com/photon/4.0/GA/iso/photon-4.0-1526e30ba.iso) 

`root@photon-6c5d42ddb1f2 [ ~ ]# rpm-ostree update`
`⠠ Receiving objects: 99% (2950/2952) 3.9 MB/s 120.0 MB `
`Receiving objects: 99% (2950/2952) 3.9 MB/s 120.0 MB... done`
`Staging deployment... done`
`Upgraded:`
 ` audit 2.8.5-6.ph4 -> 2.8.5-7.ph4`
`  cpio 2.13-3.ph4 -> 2.13-4.ph4`
 ` curl 7.74.0-1.ph4 -> 7.75.0-1.ph4`
 ` curl-libs 7.74.0-1.ph4 -> 7.75.0-1.ph4`
 ` glib 2.66.1-1.ph4 -> 2.68.0-1.ph4`
 ` glib-networking 2.66.0-1.ph4 -> 2.66.0-2.ph4`
 ` glibc 2.32-2.ph4 -> 2.32-5.ph4`
 ` glibc-iconv 2.32-2.ph4 -> 2.32-5.ph4`
 ` gnutls 3.6.15-3.ph4 -> 3.6.15-4.ph4`
 ` gobject-introspection 1.66.0-3.ph4 -> 1.66.0-4.ph4`
 ` grub2 2.04-2.ph4 -> 2.06~rc1-1.ph4`
 ` grub2-efi 2.04-2.ph4 -> 2.06~rc1-1.ph4`
 ` grub2-efi-image 2.04-2.ph4 -> 2.06~rc1-1.ph4`
 ` grub2-pc 2.04-2.ph4 -> 2.06~rc1-1.ph4`
 ` libxslt 1.1.34-2.ph4 -> 1.1.34-3.ph4`
 ` linux 5.10.4-16.ph4 -> 5.10.25-3.ph4`
 ` lua 5.3.5-1.ph4 -> 5.3.6-1.ph4`
 ` mozjs 78.3.1-2.ph4 -> 78.3.1-3.ph4`
 ` nettle 3.6-1.ph4 -> 3.7.2-1.ph4`
 ` openldap 2.4.53-3.ph4 -> 2.4.57-1.ph4`
 ` openssl 1.1.1i-2.ph4 -> 1.1.1k-1.ph4`
 ` python3 3.9.1-2.ph4 -> 3.9.1-4.ph4`
 ` python3-gobject-introspection 1.66.0-3.ph4 -> 1.66.0-4.ph4`
 ` python3-libs 3.9.1-2.ph4 -> 3.9.1-4.ph4`
 ` python3-setuptools 3.9.1-2.ph4 -> 3.9.1-4.ph4`
 ` python3-xml 3.9.1-2.ph4 -> 3.9.1-4.ph4`
 ` rpm 4.16.1.2-1.ph4 -> 4.16.1.2-2.ph4`
 ` rpm-libs 4.16.1.2-1.ph4 -> 4.16.1.2-2.ph4`
 ` systemd 247.3-1.ph4 -> 247.6-1.ph4`
 ` systemd-libs 247.3-1.ph4 -> 247.6-1.ph4`
 ` systemd-pam 247.3-1.ph4 -> 247.6-1.ph4`
 ` systemd-rpm-macros 247.3-1.ph4 -> 247.6-1.ph4`
 ` systemd-udev 247.3-1.ph4 -> 247.6-1.ph4`
`Run "systemctl reboot" to start a reboot`
`root@photon-6c5d42ddb1f2 [ ~ ]# systemctl reboot`

After reboot:

`root@photon-6c5d42ddb1f2 [ ~ ]# uname -a`
`Linux photon-6c5d42ddb1f2 5.10.25-3.ph4 #1-photon SMP Thu Apr 22 03:01:20 UTC 2021 x86_64 GNU/Linux`

Could you please point out the exact error which you have faced along with error logs if possible?
Also , it would be great if you could share the steps which you have followed to reproduce the issue if there is any.

Thanks,
Ankit

**Comment by timothybrush** [comment]
I found the issue.  It was with my template and has not been fixed.  Apologies for any inconvenience.
